# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'openalea.opencv'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = 'M.Mielewczik, C.Fournier, C. Pradal'
__institutes__ = None
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = 'opencv_icon.png'
__alias__ = []


__all__ = []














    

