# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'openalea.opencv.feature_detection'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = 'M.Mielewczik, C.Fournier, C. Pradal'
__institutes__ = None
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = 'feature.png'
__alias__ = []

__all__ = [ 'opencv2_cornerHarris','opencv2_cannyEdge',]

bordertype = ['BORDER_DEFAULT','BORDER_CONSTANT', 'BORDER_ISOLATED', 'BORDER_REFLECT', 'BORDER_REFLECT101', 'BORDER_REFLECT_101','BORDER_REPLICATE', 'BORDER_TRANSPARENT', 'BORDER_WRAP']               


opencv2_cannyEdge = Factory(name='cannyEdge',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing',
                nodemodule='openalea.opencv.nodes',
                nodeclass='cannyEdge',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_cornerHarris = Factory(name='cornerHarris',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing',
                nodemodule='openalea.opencv.nodes',
                nodeclass='cornerHarris',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_cornerEigenValsAndVecs = Factory(name='cornerEigenValsAndVecs',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing',
                nodemodule='openalea.opencv.nodes',
                nodeclass='cornerEigenValsAndVecs',
                inputs=[{'interface': IFileStr, 'name': 'Image'},
                        {'interface': IInt(1,3), 'name':'blockSize', 'value':(0)},
                        {'interface': IInt(1,3), 'name':'ksize', 'value':(1)},
                        {'interface': IEnumStr(enum=bordertype), 'name': 'BorderType', 'value': 'BORDER_DEFAULT'}],
                outputs=[{'interface': None, 'name': 'eigenvv'}], #Bugfixed by changing the brackets
                widgetmodule=None,
                widgetclass=None,
               )
                
__all__.append('opencv2_cornerEigenValsAndVecs')

opencv2_cornerSubPix = Factory(name='cornerSubPix',
 authors=' (M.Mielewczik)',
                description='',
                category='Image Processing',
                nodemodule='openalea.opencv.nodes',
                nodeclass='cornerSubPix_node',
                inputs=[{'interface': IFileStr, 'name': 'Image'},
                        {'interface': IFileStr, 'name': 'Corners'},
                        {'interface': ISequence, 'name':'patternsSize', 'value':(5,5)},
                        {'interface': ISequence, 'name':'patternsSize', 'value':(-1,-1)},
                        {'interface': IFileStr, 'name': 'Image'}],
                outputs=[{'interface': None, 'name': 'found'},
                        {'interface': None, 'name': 'corners'}], #Bugfixed by changing the brackets
                widgetmodule=None,
                widgetclass=None,
               )
               
__all__.append('opencv2_cornerSubPix')