# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'openalea.opencv.color_transform'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = 'M.Mielewczik, C.Fournier, C. Pradal'
__institutes__ = None
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = 'colorspace.png'
__alias__ = []


# complete flag list of cvtColor
#color_flags = [i for i in dir(cv2) if i.startswith('COLOR_')]
color_flags=['COLOR_BAYER_BG2BGR','COLOR_BAYER_BG2BGR_VNG','COLOR_BAYER_BG2GRAY','COLOR_BAYER_BG2RGB','COLOR_BAYER_BG2RGB_VNG','COLOR_BAYER_GB2BGR','COLOR_BAYER_GB2BGR_VNG','COLOR_BAYER_GB2GRAY','COLOR_BAYER_GB2RGB','COLOR_BAYER_GB2RGB_VNG','COLOR_BAYER_GR2BGR','COLOR_BAYER_GR2BGR_VNG','COLOR_BAYER_GR2GRAY','COLOR_BAYER_GR2RGB','COLOR_BAYER_GR2RGB_VNG','COLOR_BAYER_RG2BGR','COLOR_BAYER_RG2BGR_VNG','COLOR_BAYER_RG2GRAY','COLOR_BAYER_RG2RGB','COLOR_BAYER_RG2RGB_VNG',
 'COLOR_BGR2BGR555','COLOR_BGR2BGR565','COLOR_BGR2BGRA','COLOR_BGR2GRAY','COLOR_BGR2HLS','COLOR_BGR2HLS_FULL','COLOR_BGR2HSV','COLOR_BGR2HSV_FULL','COLOR_BGR2LAB','COLOR_BGR2LUV','COLOR_BGR2RGB','COLOR_BGR2RGBA','COLOR_BGR2XYZ','COLOR_BGR2YCR_CB','COLOR_BGR2YUV',
 'COLOR_BGR2YUV_I420','COLOR_BGR2YUV_IYUV','COLOR_BGR2YUV_YV12','COLOR_BGR5552BGR','COLOR_BGR5552BGRA','COLOR_BGR5552GRAY','COLOR_BGR5552RGB','COLOR_BGR5552RGBA','COLOR_BGR5652BGR','COLOR_BGR5652BGRA','COLOR_BGR5652GRAY','COLOR_BGR5652RGB','COLOR_BGR5652RGBA',
 'COLOR_BGRA2BGR','COLOR_BGRA2BGR555','COLOR_BGRA2BGR565','COLOR_BGRA2GRAY','COLOR_BGRA2RGB','COLOR_BGRA2RGBA','COLOR_BGRA2YUV_I420','COLOR_BGRA2YUV_IYUV','COLOR_BGRA2YUV_YV12',
 'COLOR_COLORCVT_MAX',
 'COLOR_GRAY2BGR','COLOR_GRAY2BGR555','COLOR_GRAY2BGR565','COLOR_GRAY2BGRA','COLOR_GRAY2RGB','COLOR_GRAY2RGBA',
 'COLOR_HLS2BGR','COLOR_HLS2BGR_FULL','COLOR_HLS2RGB','COLOR_HLS2RGB_FULL',
 'COLOR_HSV2BGR','COLOR_HSV2BGR_FULL','COLOR_HSV2RGB','COLOR_HSV2RGB_FULL',
 'COLOR_LAB2BGR','COLOR_LAB2LBGR','COLOR_LAB2LRGB','COLOR_LAB2RGB',
 'COLOR_LBGR2LAB','COLOR_LBGR2LUV','COLOR_LRGB2LAB','COLOR_LRGB2LUV',
 'COLOR_LUV2BGR','COLOR_LUV2LBGR','COLOR_LUV2LRGB','COLOR_LUV2RGB',
 'COLOR_M_RGBA2RGBA',
 'COLOR_RGB2BGR','COLOR_RGB2BGR555','COLOR_RGB2BGR565','COLOR_RGB2BGRA','COLOR_RGB2GRAY','COLOR_RGB2HLS','COLOR_RGB2HLS_FULL','COLOR_RGB2HSV','COLOR_RGB2HSV_FULL','COLOR_RGB2LAB','COLOR_RGB2LUV','COLOR_RGB2RGBA','COLOR_RGB2XYZ','COLOR_RGB2YCR_CB','COLOR_RGB2YUV','COLOR_RGB2YUV_I420','COLOR_RGB2YUV_IYUV','COLOR_RGB2YUV_YV12',
 'COLOR_RGBA2BGR','COLOR_RGBA2BGR555','COLOR_RGBA2BGR565','COLOR_RGBA2BGRA','COLOR_RGBA2GRAY','COLOR_RGBA2M_RGBA','COLOR_RGBA2RGB','COLOR_RGBA2YUV_I420','COLOR_RGBA2YUV_IYUV','COLOR_RGBA2YUV_YV12',
 'COLOR_XYZ2BGR','COLOR_XYZ2RGB',
 'COLOR_YCR_CB2BGR','COLOR_YCR_CB2RGB',
 'COLOR_YUV2BGR','COLOR_YUV2BGRA_I420','COLOR_YUV2BGRA_IYUV','COLOR_YUV2BGRA_NV12','COLOR_YUV2BGRA_NV21','COLOR_YUV2BGRA_UYNV','COLOR_YUV2BGRA_UYVY','COLOR_YUV2BGRA_Y422','COLOR_YUV2BGRA_YUNV','COLOR_YUV2BGRA_YUY2','COLOR_YUV2BGRA_YUYV','COLOR_YUV2BGRA_YV12',
 'COLOR_YUV2BGRA_YVYU','COLOR_YUV2BGR_I420','COLOR_YUV2BGR_IYUV','COLOR_YUV2BGR_NV12','COLOR_YUV2BGR_NV21','COLOR_YUV2BGR_UYNV','COLOR_YUV2BGR_UYVY','COLOR_YUV2BGR_Y422','COLOR_YUV2BGR_YUNV','COLOR_YUV2BGR_YUY2','COLOR_YUV2BGR_YUYV','COLOR_YUV2BGR_YV12',
 'COLOR_YUV2BGR_YVYU','COLOR_YUV2GRAY_420','COLOR_YUV2GRAY_I420','COLOR_YUV2GRAY_IYUV','COLOR_YUV2GRAY_NV12','COLOR_YUV2GRAY_NV21','COLOR_YUV2GRAY_UYNV','COLOR_YUV2GRAY_UYVY','COLOR_YUV2GRAY_Y422','COLOR_YUV2GRAY_YUNV','COLOR_YUV2GRAY_YUY2','COLOR_YUV2GRAY_YUYV',
 'COLOR_YUV2GRAY_YV12','COLOR_YUV2GRAY_YVYU','COLOR_YUV2RGB','COLOR_YUV2RGBA_I420','COLOR_YUV2RGBA_IYUV','COLOR_YUV2RGBA_NV12','COLOR_YUV2RGBA_NV21','COLOR_YUV2RGBA_UYNV',
 'COLOR_YUV2RGBA_UYVY','COLOR_YUV2RGBA_Y422','COLOR_YUV2RGBA_YUNV','COLOR_YUV2RGBA_YUY2','COLOR_YUV2RGBA_YUYV','COLOR_YUV2RGBA_YV12','COLOR_YUV2RGBA_YVYU','COLOR_YUV2RGB_I420','COLOR_YUV2RGB_IYUV','COLOR_YUV2RGB_NV12','COLOR_YUV2RGB_NV21','COLOR_YUV2RGB_UYNV',
 'COLOR_YUV2RGB_UYVY','COLOR_YUV2RGB_Y422','COLOR_YUV2RGB_YUNV','COLOR_YUV2RGB_YUY2','COLOR_YUV2RGB_YUYV','COLOR_YUV2RGB_YV12','COLOR_YUV2RGB_YVYU','COLOR_YUV420P2BGR','COLOR_YUV420P2BGRA','COLOR_YUV420P2GRAY','COLOR_YUV420P2RGB','COLOR_YUV420P2RGBA',
 'COLOR_YUV420SP2BGR','COLOR_YUV420SP2BGRA','COLOR_YUV420SP2GRAY','COLOR_YUV420SP2RGB','COLOR_YUV420SP2RGBA']

__all__ = ['opencv2_lab2bgr', 'opencv2_lab2rgb', 'opencv2_rgb2lab', 'opencv2_bgr2lab', 'opencv2_luv2rgb', 'opencv2_luv2bgr', 'opencv2_rgb2luv', 'opencv2_bgr2luv', 'opencv2_rgb2gray',  'opencv2_bgr2gray' , 'opencv2_rgb2hsv','opencv2_bgr2hsv',]


opencv2_cvtColor = Factory(name='cvtColor',
                authors='(C.Fournier)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.nodes',
                nodeclass='cvtColor',
                inputs=[{'interface': None, 'name': 'Image'},
                {'interface': IEnumStr(enum=color_flags), 'name': 'Flag'},],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )
__all__.append('opencv2_cvtColor')

opencv2_rgb2hsv = Factory(name='rgb2hsv',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='rgb2hsv',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_bgr2hsv = Factory(name='bgr2hsv',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='bgr2hsv',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )               
               
opencv2_bgr2luv = Factory(name='bgr2luv',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='bgr2luv',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )
__all__.append('opencv2_bgr2luv')

opencv2_bgr2rgb = Factory(name='bgr2rgb',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='bgr2rgb',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )               
               

__all__.append('opencv2_bgr2rgb')
               
opencv2_rgb2luv = Factory(name='rgb2luv',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='rgb2luv',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_luv2bgr = Factory(name='luv2bgr',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='luv2bgr',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_luv2rgb = Factory(name='luv2rgb',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='luv2rgb',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_bgr2lab = Factory(name='bgr2lab',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='bgr2lab',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_rgb2lab = Factory(name='rgb2lab',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='rgb2lab',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_lab2bgr = Factory(name='lab2bgr',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='lab2bgr',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_lab2rgb = Factory(name='lab2rgb',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='lab2rgb',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )


opencv2_bgr2gray = Factory(name='bgr2gray',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='bgr2gray',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )

opencv2_rgb2gray = Factory(name='rgb2gray',
                authors=' (M.Mielewczik)',
                description='',
                category='Image Processing, Colorspace_conversion',
                nodemodule='openalea.opencv.extension',
                nodeclass='rgb2gray',
                #inputs=[{'interface': IFileStr, 'name': 'Image'}],
                outputs=({'interface': None, 'name': 'out'},),
                widgetmodule=None,
                widgetclass=None,
               )
