# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'openalea.opencv.camera_calibration'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = 'M.Mielewczik, C.Fournier, C. Pradal'
__institutes__ = None
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = 'calib3d_icon.png'
__alias__ = []


__all__ = []



opencv2_findChessboardCorners = Factory(name='findChessboardCorners',
 authors=' (M.Mielewczik)',
                description='',
                category='Image Processing',
                nodemodule='openalea.opencv.nodes',
                nodeclass='findChessboardCorners',
                inputs=[{'interface': IFileStr, 'name': 'Image'},
                        {'interface': ITuple, 'name':'patternsSize', 'value': "(8,6)"}],
                outputs=[{'interface': None, 'name': 'found'},
                        {'interface': None, 'name': 'corners'}], #Bugfixed by changing the brackets
                widgetmodule=None,
                widgetclass=None,
               )
               
__all__.append('opencv2_findChessboardCorners')

opencv2_drawChessboardCorners = Factory(name='drawChessboardCorners',
 authors=' (M.Mielewczik)',
                description='',
                category='Image Processing',
                nodemodule='openalea.opencv.nodes',
                nodeclass='drawChessboardCorners_node',
                inputs=[{'interface': IFileStr, 'name': 'Image'},
                        {'interface': ISequence, 'name':'patternsSize', 'value':(8,6)},
                        {'interface': IInt(1,3), 'name':'corners', 'value':(0)},
                        {'interface': IInt(1,3), 'name':'patternWasFound', 'value':(0)}],
                outputs=[{'interface': None, 'name': 'found'},
                        {'interface': None, 'name': 'corners'}], #Bugfixed by changing the brackets
                widgetmodule=None,
                widgetclass=None,
               )
               
__all__.append('opencv2_drawChessboardCorners')













    

